import Link from "next/link";
import type { Metadata } from "next";

import { Button } from "@/components/ui/button";
import { Card, CardHeading } from "@/components/ui/card";
import {
  BookmarkIcon,
  BriefcaseIcon,
  CoinIcon,
  ProfileIcon,
  RouteIcon,
  SearchIcon,
  SlidersIcon,
  SyncIcon,
  TelegramIcon,
} from "@/components/landing/icons";
import { getAuthUser } from "@/lib/auth/dal";
import { MAIN_MENU_KEYBOARD } from "@/lib/telegram/menu";

const TITLE = "Search4Jobs — AI-Matched Job Search";
const DESCRIPTION =
  "Discover real job listings matched to your skills and preferences. Search from your dashboard or connect your own Telegram bot. Start with 5 free daily credits.";

export const metadata: Metadata = {
  // `absolute` bypasses the root layout's title template so the homepage
  // renders exactly this title instead of "...| Search4Jobs".
  title: { absolute: TITLE },
  description: DESCRIPTION,
  alternates: { canonical: "/" },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: "/",
    siteName: "Search4Jobs",
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
};

const STEPS = [
  {
    icon: ProfileIcon,
    label: "Step 1",
    title: "Set up your profile",
    description:
      "Add your skills, experience, CV, and job preferences so Search4Jobs can understand what you are looking for.",
  },
  {
    icon: SearchIcon,
    label: "Step 2",
    title: "Discover relevant opportunities",
    description: "Search real job listings and have them evaluated against your profile and preferences.",
  },
  {
    icon: RouteIcon,
    label: "Step 3",
    title: "Search your way",
    description: "Use the web dashboard or connect your own Telegram bot to access your job-search tools.",
  },
];

const BENEFITS = [
  {
    icon: BriefcaseIcon,
    title: "Real job listings",
    description:
      "Discover real job opportunities sourced from Adzuna. Listing details come from the source; relevance scores and explanations are generated by AI on top of them.",
  },
  {
    icon: SlidersIcon,
    title: "AI-powered matching",
    description:
      "Get job listings evaluated against your skills, experience, and preferences — a relevance signal to help you prioritize, not a guarantee of suitability or employment.",
  },
  {
    icon: TelegramIcon,
    title: "Your own Telegram bot",
    description: "Connect a bot you create with BotFather and use it to search for opportunities and manage your job search.",
  },
  {
    icon: SyncIcon,
    title: "One account, two ways to search",
    description: "Your dashboard and connected Telegram bot use the same account, credits, and job-search history.",
  },
  {
    icon: BookmarkIcon,
    title: "Save jobs and revisit them",
    description: "Keep track of opportunities you want to explore further, from either the dashboard or the bot.",
  },
  {
    icon: CoinIcon,
    title: "Free daily credits",
    description: "Start with 5 free credits each day. Need more? Purchase a credit pack whenever you're ready.",
  },
];

function MatchBadge({ children }: { children: React.ReactNode }) {
  return (
    <span className="inline-flex items-center rounded-full bg-brand/10 px-2.5 py-0.5 text-xs font-medium text-brand">
      {children}
    </span>
  );
}

export default async function Home() {
  const user = await getAuthUser();

  return (
    <div className="flex min-h-screen flex-col bg-background">
      <header className="flex items-center justify-between border-b border-border px-6 py-4">
        <span className="text-lg font-semibold">Search4Jobs</span>
        <nav className="flex items-center gap-3">
          {user ? (
            <Link href="/dashboard">
              <Button>Go to dashboard</Button>
            </Link>
          ) : (
            <>
              <Link
                href="/login"
                className="rounded-md text-sm font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand focus-visible:ring-offset-2 focus-visible:ring-offset-background"
              >
                Sign in
              </Link>
              <Link href="/signup">
                <Button>Get started free</Button>
              </Link>
            </>
          )}
        </nav>
      </header>

      <main className="flex-1">
        {/* Hero */}
        <section className="mx-auto grid max-w-6xl gap-12 px-6 py-16 sm:py-24 lg:grid-cols-[1.1fr_0.9fr] lg:items-center">
          <div className="mx-auto max-w-xl text-center lg:mx-0 lg:text-left">
            <p className="text-xs font-semibold tracking-widest text-brand uppercase">
              Your job search, made more relevant
            </p>
            <h1 className="mt-3 text-4xl font-semibold tracking-tight text-balance sm:text-5xl">
              Find jobs that fit your skills.
            </h1>
            <p className="mt-5 text-lg text-muted text-pretty">
              Search real job listings and get them ranked against your skills, experience, and
              preferences. Manage your search from the dashboard or connect your own Telegram bot
              to find and track opportunities on the go.
            </p>
            <div className="mt-8 flex flex-col items-center gap-3 sm:flex-row lg:justify-start">
              <Link href="/signup" className="w-full sm:w-auto">
                <Button className="w-full px-6 py-3 text-base sm:w-auto">Get started free</Button>
              </Link>
              <Link href="/login" className="w-full sm:w-auto">
                <Button variant="secondary" className="w-full px-6 py-3 text-base sm:w-auto">
                  Sign in
                </Button>
              </Link>
            </div>
            <p className="mt-4 text-sm text-muted">Start with 5 free credits every day.</p>
          </div>

          <div aria-hidden="true" className="mx-auto w-full max-w-sm lg:mx-0">
            <div className="relative">
              <Card className="relative z-10">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <p className="font-semibold">Frontend Engineer</p>
                    <p className="text-sm text-muted">Remote · Full-time</p>
                  </div>
                  <MatchBadge>91% match</MatchBadge>
                </div>
                <p className="mt-3 text-sm text-muted">
                  Matches your React and TypeScript experience, and your remote-work preference.
                </p>
              </Card>
              <Card className="absolute -bottom-6 -left-6 hidden w-11/12 opacity-90 sm:block">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <p className="font-semibold">Backend Engineer</p>
                    <p className="text-sm text-muted">Hybrid · Contract</p>
                  </div>
                  <MatchBadge>78% match</MatchBadge>
                </div>
              </Card>
            </div>
          </div>
        </section>

        {/* How it works */}
        <section className="border-t border-border bg-surface/50 px-6 py-16 sm:py-20">
          <div className="mx-auto max-w-5xl">
            <h2 className="text-center text-2xl font-semibold sm:text-3xl">How it works</h2>
            <div className="mt-10 grid gap-8 sm:grid-cols-3">
              {STEPS.map((step) => (
                <div key={step.title} className="text-center sm:text-left">
                  <div className="mx-auto flex h-11 w-11 items-center justify-center rounded-lg bg-brand/10 text-brand sm:mx-0">
                    <step.icon className="h-5 w-5" />
                  </div>
                  <p className="mt-4 text-xs font-semibold tracking-widest text-muted uppercase">
                    {step.label}
                  </p>
                  <h3 className="mt-1 font-semibold">{step.title}</h3>
                  <p className="mt-2 text-sm text-muted">{step.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Product benefits */}
        <section className="px-6 py-16 sm:py-20">
          <div className="mx-auto max-w-5xl">
            <h2 className="text-center text-2xl font-semibold sm:text-3xl">Everything you need to search smarter</h2>
            <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {BENEFITS.map((benefit) => (
                <Card key={benefit.title}>
                  <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-brand/10 text-brand">
                    <benefit.icon className="h-4.5 w-4.5" />
                  </div>
                  <CardHeading className="mt-3">{benefit.title}</CardHeading>
                  <p className="mt-2 text-sm text-muted">{benefit.description}</p>
                </Card>
              ))}
            </div>
          </div>
        </section>

        {/* Telegram */}
        <section className="border-y border-border bg-surface/50 px-6 py-16 sm:py-20">
          <div className="mx-auto grid max-w-5xl items-center gap-10 lg:grid-cols-2">
            <div>
              <h2 className="text-2xl font-semibold sm:text-3xl">Your job search, right inside Telegram.</h2>
              <p className="mt-4 text-muted">
                Connect your own Telegram bot and use simple buttons to find jobs, update
                preferences, review matches, save opportunities, and check your credits. Your bot
                connects to the same Search4Jobs account you use on the web.
              </p>
              <Link href="/signup" className="mt-6 inline-block">
                <Button>Get started</Button>
              </Link>
            </div>
            <div aria-hidden="true">
              <Card className="mx-auto max-w-sm">
                <div className="flex items-center gap-2 border-b border-border pb-3">
                  <div className="flex h-7 w-7 items-center justify-center rounded-full bg-brand text-brand-foreground">
                    <TelegramIcon className="h-4 w-4" />
                  </div>
                  <p className="text-sm font-medium">Your Search4Jobs bot</p>
                </div>
                <div className="mt-3 grid grid-cols-2 gap-2">
                  {MAIN_MENU_KEYBOARD.keyboard.flat().map((label) => (
                    <div
                      key={label}
                      className="truncate rounded-md border border-border bg-surface px-2.5 py-2 text-center text-xs font-medium"
                    >
                      {label}
                    </div>
                  ))}
                </div>
              </Card>
            </div>
          </div>
        </section>

        {/* Free credits / getting started */}
        <section className="px-6 py-16 sm:py-20">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-2xl font-semibold sm:text-3xl">Start searching for free.</h2>
            <p className="mt-4 text-muted">
              Create your account, complete your profile, and start exploring job opportunities
              with 5 free credits every day. Need more? You can purchase additional credits when
              you are ready.
            </p>
          </div>
        </section>

        {/* Final CTA */}
        <section className="border-t border-border bg-brand/5 px-6 py-16 sm:py-20">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-2xl font-semibold sm:text-3xl">Make your next job search more focused.</h2>
            <p className="mt-4 text-muted">
              Set up your profile, tell us what you are looking for, and start exploring real
              opportunities matched to your preferences.
            </p>
            <Link href="/signup" className="mt-6 inline-block">
              <Button className="px-6 py-3 text-base">Create your free account</Button>
            </Link>
          </div>
        </section>
      </main>

      <footer className="border-t border-border px-6 py-8 text-center text-sm text-muted">
        <p>© {new Date().getFullYear()} Search4Jobs. Job listings are sourced from Adzuna.</p>
      </footer>
    </div>
  );
}
